"""Session-variable (GUC) helpers a declared policy's expression reads through `current_setting`.

Every value a policy compares against session state, the acting principal, a narrowing scope, a
bypass flag, is a Postgres GUC (`SET LOCAL` / `current_setting`), never a bind parameter: a
policy's compiled clause carries no placeholders, so `current_setting` is the only way it reaches
per-connection state at all. Upstream (DelfinaCare/rls, MIT) hardcoded this namespace to a module
constant, `_CONDITION_ARGS_PREFIX = "rls"`; here the prefix is a parameter on every call instead, so
more than one registry can share a process without colliding, and a caller free to pick its own
namespace (`app`, `tenant`, whatever fits its schema) rather than being stuck with `rls.`.
"""

import sqlalchemy as sa
from sqlalchemy.sql.elements import ColumnElement
from sqlalchemy.sql.type_api import TypeEngine


def current_setting(name: str, type_: TypeEngine, prefix: str) -> ColumnElement:
    """A scalar-subquery read of one `<prefix>.<name>` GUC, `NULL` when the session never set it.

    Wrapped in `SELECT` as a scalar subquery rather than called bare so Postgres plans the read as
    one `InitPlan`, evaluated once per query regardless of how many candidate rows the policy scans,
    instead of once per row a bare function call in the `USING` clause would cost. Labeled
    explicitly so the compiled text names a fixed column (`AS uid`) rather than an autogenerated
    `anon_1`-style label whose spelling would depend on which other anonymous expressions share the
    same compile call.

    name: the GUC's own name under `prefix`, e.g. `uid` for `app.uid`.
    type_: the SQLAlchemy type to cast the setting's text value to.
    prefix: the GUC namespace this registry claims, e.g. `app` or `rls`.
    """
    read = sa.func.nullif(sa.func.current_setting(f"{prefix}.{name}", True), "")
    return sa.select(read.cast(type_).label(name)).scalar_subquery()


def bypass_clause(prefix: str, name: str = "bypass_rls") -> ColumnElement:
    """An opt-in `<prefix>.<name>` boolean escape a policy may `OR` into its own predicate.

    No policy this library builds carries a bypass branch by default, unlike upstream's
    `Policy.allow_bypass_rls`, which stitched a matching `OR` clause into every generated policy
    whether a caller wanted the escape hatch or not. A policy that wants one composes this helper
    into its own `using`/`check` expression explicitly, and `RlsSession.bypass_rls()` sets the flag
    this reads.

    prefix: the GUC namespace this registry claims.
    name: the flag's own name under `prefix`.
    """
    read = sa.func.nullif(sa.func.current_setting(f"{prefix}.{name}", True), "")
    return sa.func.coalesce(read.cast(sa.Boolean()), sa.false())
