name: Code Quality

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"

  static-analysis:
    runs-on: ubuntu-latest
    name: Static Analysis
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          cache: pip
          python-version: 3.12
      - name: Install
        run: pip install -e ".[dev]"
      - name: Run Mypy
        run: mypy .
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        include:
          - python-version: "3.14"
            postgres-version: "16"
          - python-version: "3.14"
            postgres-version: "17"
          - python-version: "3.14"
            postgres-version: "18"
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install PostgreSQL ${{ matrix.postgres-version }}
        if: matrix.postgres-version
        run: |
          sudo install -d /usr/share/postgresql-common/pgdg
          sudo curl -fsSo /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc https://www.postgresql.org/media/keys/ACCC4CF8.asc
          sudo sh -c 'echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          sudo apt-get update
          sudo apt-get install -y postgresql-${{ matrix.postgres-version }}
          echo "/usr/lib/postgresql/${{ matrix.postgres-version }}/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: pip install -e ".[dev]"
      - name: Run unit tests
        env:
          PYTHONPATH: "${{ github.workspace }}/test"
        run: python3 -m unittest discover
